//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.DocumentoHist = new HashSet<DocumentoHist>();
        }
    
        public int IdDocumento { get; set; }
        public int IdSubArea { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual SubArea SubArea { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<DocumentoHist> DocumentoHist { get; set; }
        public virtual TipoDocumento TipoDocumento1 { get; set; }
    }
}
