//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.DocumentoHist = new HashSet<DocumentoHist>();
        }
    
        public int IdDocumento { get; set; }
        public int IdSubArea { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual SubArea SubArea { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<DocumentoHist> DocumentoHist { get; set; }
        public virtual TipoDocumento TipoDocumento1 { get; set; }
    }
}
