//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoHist
    {
        public int IdDocumento { get; set; }
        public int IdHistorico { get; set; }
        public string NombreDocumento { get; set; }
        public string UrlDocumento { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public bool IndicadorHabilitado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Documento Documento { get; set; }
    }
}
