//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoHist
    {
        public int IdDocumento { get; set; }
        public int IdHistorico { get; set; }
        public string NombreDocumento { get; set; }
        public string UrlDocumento { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificaciom { get; set; }
        public bool IndicadorHabilitado { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
