//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long IDLog { get; set; }
        public string Usuario { get; set; }
        public string TipoLog { get; set; }
        public string Funcion { get; set; }
        public string RegistroLog { get; set; }
        public string RequestLog { get; set; }
        public System.DateTime FechaLog { get; set; }
    }
}
