//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public Mantenimiento()
        {
            this.MenuFooter = new HashSet<MenuFooter>();
        }
    
        public int MantenimientoId { get; set; }
        public string MantenimientoLogo { get; set; }
        public string MantenimientoTelefono { get; set; }
        public string MantenimientoMenuFooter { get; set; }
        public string MantenimientoSobreNosotros { get; set; }
        public string MantenimientoDerechosReservados { get; set; }
        public System.DateTime MantenimientoFechaActualizacion { get; set; }
    
        public virtual ICollection<MenuFooter> MenuFooter { get; set; }
    }
}
