//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuFooter
    {
        public int MenuFooterId { get; set; }
        public int MantenimientoId { get; set; }
        public string MenuFooterName { get; set; }
        public string MenuFooterUrl { get; set; }
        public int MenuFooterPosition { get; set; }
        public bool MenuFooterIsSuperAdmin { get; set; }
        public bool MenuFooterStatus { get; set; }
    
        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
