//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpeCarEntities : DbContext
    {
        public OpeCarEntities()
            : base("name=OpeCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AreaHist> AreaHist { get; set; }
        public DbSet<DocumentoHist> DocumentoHist { get; set; }
        public DbSet<SubAreaHist> SubAreaHist { get; set; }
        public DbSet<TipoArea> TipoArea { get; set; }
        public DbSet<TipoDocumento> TipoDocumento { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<SubArea> SubArea { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<TipoSeccion> TipoSeccion { get; set; }
        public DbSet<Seccion> Seccion { get; set; }
        public DbSet<Enlace> Enlace { get; set; }
        public DbSet<Mantenimiento> Mantenimiento { get; set; }
        public DbSet<MenuFooter> MenuFooter { get; set; }
        public DbSet<Permiso> Permiso { get; set; }
        public DbSet<Log> Log { get; set; }
    }
}
