//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int IdUsuario { get; set; }
        public byte IdRol { get; set; }
        public int IdArea { get; set; }
        public int IdHistorico { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaIniVig { get; set; }
        public Nullable<System.DateTime> FechaFinVig { get; set; }
        public int IdSubArea { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
