//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int IdTipoDocumento { get; set; }
        public string Descripción { get; set; }
        public bool IndicadorHabilitado { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
