//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.Documento = new HashSet<Documento>();
            this.Documento1 = new HashSet<Documento>();
        }
    
        public int IdTipoDocumento { get; set; }
        public string Descripción { get; set; }
        public bool IndicadorHabilitado { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Documento> Documento1 { get; set; }
    }
}
