//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSeccion
    {
        public TipoSeccion()
        {
            this.Seccion = new HashSet<Seccion>();
        }
    
        public short IdTipoSeccion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Seccion> Seccion { get; set; }
    }
}
