//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpeCar.GestionDocumental.Models.Infrastructure.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.AreaHist = new HashSet<AreaHist>();
            this.DocumentoHist = new HashSet<DocumentoHist>();
            this.SubAreaHist = new HashSet<SubAreaHist>();
            this.Usuario11 = new HashSet<Usuario>();
            this.Documento = new HashSet<Documento>();
            this.Seccion = new HashSet<Seccion>();
            this.Seccion1 = new HashSet<Seccion>();
            this.Permiso = new HashSet<Permiso>();
        }
    
        public int IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<bool> IndicadorSistema { get; set; }
    
        public virtual ICollection<AreaHist> AreaHist { get; set; }
        public virtual ICollection<DocumentoHist> DocumentoHist { get; set; }
        public virtual ICollection<SubAreaHist> SubAreaHist { get; set; }
        public virtual ICollection<Usuario> Usuario11 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Seccion> Seccion { get; set; }
        public virtual ICollection<Seccion> Seccion1 { get; set; }
        public virtual ICollection<Permiso> Permiso { get; set; }
    }
}
